# For conda build
package:
  name: pydqed
  version: "1.0.0"

source:
  path: .

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }} # number of commits since last git tag (which should be last change to __version__)
 

requirements:
  build:
    - gcc # [unix]
    - python
    - setuptools
    - cython ==0.21
    - numpy
  run:
    - libgcc # [unix]
    - python
    - numpy

test:
  files:
    - test.py
  imports:
    - pydqed
  commands:
    - python test.py

about:
  home: http://github.com/GreenGroup/PyDQED
  license: MIT
  summary: "A Python wrapper to the DQED bounded constrained nonlinear optimization code."
