# For conda build
package:
  name: pydqed
  version: '1.0.4'

source:
  path: ../

build:
  string: py{{ CONDA_PY }}h{{ PKG_HASH }}npy{{ NPY_VER }}_{{ PKG_BUILDNUM }}
 

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - python
    - cython
    - numpy
    - setuptools
  run:
    - python
    # https://conda-forge.org/docs/maintainer/knowledge_base/#building-against-numpy
    - {{ pin_compatible('numpy') }}

test:
  source_files:
    - test.py
  imports:
    - pydqed
  commands:
    - python test.py

about:
  home: http://github.com/ReactionMechanismGenerator/PyDQED
  license: MIT
  summary: "Python wrapper to the DQED bounded constrained nonlinear optimization code."
